#ifndef PP_PLANARINIT_GLOBAL_H
#define PP_PLANARINIT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PP_PLANARINIT_LIBRARY)
#  define PP_PLANARINITSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PP_PLANARINITSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PP_PLANARINIT_GLOBAL_H
