#ifndef PP_MULTIMERGEPLANE_GLOBAL_H
#define PP_MULTIMERGEPLANE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PP_MULTIMERGEPLANE_LIBRARY)
#  define PP_MULTIMERGEPLANESHARED_EXPORT Q_DECL_EXPORT
#else
#  define PP_MULTIMERGEPLANESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PP_MULTIMERGEPLANE_GLOBAL_H
