#ifndef PP_LOADFROMFUSION_GLOBAL_H
#define PP_LOADFROMFUSION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PP_LOADFROMFUSION_LIBRARY)
#  define PP_LOADFROMFUSIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PP_LOADFROMFUSIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PP_LOADFROMFUSION_GLOBAL_H
